In [35]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [36]:
users=['Vijay','Chris','Tony','Rakesh','Seema','Ishita']
food=['Veg Burger','Pizza','White Sauce Pasta','Red Sauce Pasta','Choco Frappe','Mojito','Ice Coffee','Manchurian','Noodles','French fries','Ice Cream','Brownie']
features=['Spicy','Sweet','Drinks','Americano','Italian','Pasta','Chinese']

num_users=len(users)
num_food=len(food)
num_feat=len(features)
num_recommendation=2

In [37]:
user_review= tf.constant([
    [5,0,3,2,4,0,4,3,0,4,0,1],
    [1,2,0,2,5,4,5,0,3,2,5,0],
    [5,0,1,2,3,5,2,0,5,4,3,2],
    [3,4,1,2,4,2,0,0,3,4,5,0],
    [0,3,4,0,2,3,0,5,4,2,3,0],
    [5,0,3,4,5,3,4,0,3,4,0,5]
] ,dtype=tf.float32)

model_feat=tf.constant([
    [1,0,0,1,0,0,0],
    [1,0,0,1,1,0,0],
    [1,0,0,0,1,1,1],
    [1,0,0,0,1,1,1],
    [0,1,1,1,0,0,0],
    [1,0,1,1,0,0,0],
    [0,1,1,1,0,0,0],
    [1,0,0,0,1,0,1],
    [1,0,0,0,1,0,1],
    [1,0,0,1,1,0,0],
    [0,1,0,1,0,0,0],
    [0,1,0,1,0,0,0]
],dtype=tf.float32)

In [38]:
user_feat=tf.matmul(user_review,model_feat)
user_feat

<tf.Tensor: shape=(6, 7), dtype=float32, numpy=
array([[17.,  9.,  8., 18., 12.,  5.,  8.],
       [14., 15., 14., 24.,  9.,  2.,  5.],
       [22., 10., 10., 24., 12.,  3.,  8.],
       [19.,  9.,  6., 22., 14.,  3.,  6.],
       [21.,  5.,  5., 13., 18.,  4., 13.],
       [22., 14., 12., 26., 14.,  7., 10.]], dtype=float32)>

In [39]:
user_feat=user_feat/tf.reduce_sum(user_feat,axis=1,keepdims=True)
user_feat

<tf.Tensor: shape=(6, 7), dtype=float32, numpy=
array([[0.22077923, 0.11688311, 0.1038961 , 0.23376623, 0.15584415,
        0.06493507, 0.1038961 ],
       [0.16867469, 0.18072289, 0.16867469, 0.28915662, 0.10843374,
        0.02409638, 0.06024097],
       [0.24719101, 0.11235955, 0.11235955, 0.26966292, 0.13483146,
        0.03370786, 0.08988764],
       [0.24050634, 0.11392405, 0.07594936, 0.278481  , 0.17721519,
        0.03797468, 0.07594936],
       [0.2658228 , 0.06329114, 0.06329114, 0.16455697, 0.2278481 ,
        0.05063291, 0.16455697],
       [0.20952381, 0.13333334, 0.11428571, 0.24761905, 0.13333334,
        0.06666667, 0.0952381 ]], dtype=float32)>

In [40]:
top_user_features=tf.nn.top_k(user_feat,num_feat)[1]
top_user_features

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[3, 0, 4, 1, 2, 6, 5],
       [3, 1, 0, 2, 4, 6, 5],
       [3, 0, 4, 1, 2, 6, 5],
       [3, 0, 4, 1, 2, 6, 5],
       [0, 4, 3, 6, 1, 2, 5],
       [3, 0, 1, 4, 2, 6, 5]])>

In [41]:
for i in range(num_users):
    feature_names=[features[int(index)] for index in top_user_features[i]]
    print(users[i])
    print(feature_names)

Vijay
['Americano', 'Spicy', 'Italian', 'Sweet', 'Drinks', 'Chinese', 'Pasta']
Chris
['Americano', 'Sweet', 'Spicy', 'Drinks', 'Italian', 'Chinese', 'Pasta']
Tony
['Americano', 'Spicy', 'Italian', 'Sweet', 'Drinks', 'Chinese', 'Pasta']
Rakesh
['Americano', 'Spicy', 'Italian', 'Sweet', 'Drinks', 'Chinese', 'Pasta']
Seema
['Spicy', 'Italian', 'Americano', 'Chinese', 'Sweet', 'Drinks', 'Pasta']
Ishita
['Americano', 'Spicy', 'Sweet', 'Italian', 'Drinks', 'Chinese', 'Pasta']


In [42]:
user_ratings=tf.matmul(user_feat,tf.transpose(model_feat))
user_ratings

<tf.Tensor: shape=(6, 12), dtype=float32, numpy=
array([[0.45454544, 0.6103896 , 0.54545456, 0.54545456, 0.45454544,
        0.5584415 , 0.45454544, 0.4805195 , 0.4805195 , 0.6103896 ,
        0.35064936, 0.35064936],
       [0.45783132, 0.56626505, 0.36144575, 0.36144575, 0.6385542 ,
        0.626506  , 0.6385542 , 0.33734939, 0.33734939, 0.56626505,
        0.4698795 , 0.4698795 ],
       [0.5168539 , 0.65168536, 0.505618  , 0.505618  , 0.49438202,
        0.62921345, 0.49438202, 0.47191012, 0.47191012, 0.65168536,
        0.38202247, 0.38202247],
       [0.51898736, 0.6962025 , 0.53164554, 0.53164554, 0.4683544 ,
        0.5949367 , 0.4683544 , 0.49367088, 0.49367088, 0.6962025 ,
        0.39240506, 0.39240506],
       [0.43037975, 0.65822786, 0.70886075, 0.70886075, 0.29113925,
        0.49367088, 0.29113925, 0.65822786, 0.65822786, 0.65822786,
        0.22784811, 0.22784811],
       [0.45714286, 0.5904762 , 0.50476193, 0.50476193, 0.49523813,
        0.5714286 , 0.49523813, 0.4380

In [43]:
user_rating_new=tf.where(tf.equal(user_review, tf.zeros_like(user_review)),
                        user_ratings,
                        tf.zeros_like(tf.cast(user_review,tf.float32)))
user_rating_new

<tf.Tensor: shape=(6, 12), dtype=float32, numpy=
array([[0.        , 0.6103896 , 0.        , 0.        , 0.        ,
        0.5584415 , 0.        , 0.        , 0.4805195 , 0.        ,
        0.35064936, 0.        ],
       [0.        , 0.        , 0.36144575, 0.        , 0.        ,
        0.        , 0.        , 0.33734939, 0.        , 0.        ,
        0.        , 0.4698795 ],
       [0.        , 0.65168536, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.47191012, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4683544 , 0.49367088, 0.        , 0.        ,
        0.        , 0.39240506],
       [0.43037975, 0.        , 0.        , 0.70886075, 0.        ,
        0.        , 0.29113925, 0.        , 0.        , 0.        ,
        0.        , 0.22784811],
       [0.        , 0.5904762 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4380

In [44]:
top_food=tf.nn.top_k(user_rating_new,num_recommendation)[1]
top_food

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  5],
       [11,  2],
       [ 1,  7],
       [ 7,  6],
       [ 3,  0],
       [ 1,  7]])>

In [45]:
for i in range(num_users):
    food_names=[food[int(index)] for index in top_food[i]]
    print(users[i])
    print(food_names)

Vijay
['Pizza', 'Mojito']
Chris
['Brownie', 'White Sauce Pasta']
Tony
['Pizza', 'Manchurian']
Rakesh
['Manchurian', 'Ice Coffee']
Seema
['Red Sauce Pasta', 'Veg Burger']
Ishita
['Pizza', 'Manchurian']
